### PR TITLE
spark 3 scala 2.12 support

### PR DESCRIPTION
**Pull request by ohadbitt**
#### Pull Request Description

spark 3 scala 2.12 support

### CODE REVIEW

**Comment by ohadbitt** [comment]
Open discussion: 
should we actually change our artifact id to reflect the scala version instead of the library version ? 
other libraries have a different artifactId per scala version, but we didnt use it like that from the begining .. should we release from now on two artifacts? as in: 
  spark-kusto-connector_2.11 and spark-kusto-connector_2.12
or should we leave the old one untouched ?

**Comment by vladikbr** [comment]
> Open discussion:
> should we actually change our artifact id to reflect the scala version instead of the library version ?
> other libraries have a different artifactId per scala version, but we didnt use it like that from the begining .. should we release from now on two artifacts? as in:
> spark-kusto-connector_2.11 and spark-kusto-connector_2.12
> or should we leave the old one untouched (currently used in this PR)?

I don't know. Who knows what is the common practice?

**Comment by anagha-microsoft** [comment]
> Open discussion:
> should we actually change our artifact id to reflect the scala version instead of the library version ?
> other libraries have a different artifactId per scala version, but we didnt use it like that from the begining .. should we release from now on two artifacts? as in:
> spark-kusto-connector_2.11 and spark-kusto-connector_2.12
> or should we leave the old one untouched (currently used in this PR)?

@ohadbitt -
1.  Per our discussion, this would be self-evident and user-friendly.
kusto-spark_<n.n.n for spark version>_<n.n for Scala version only>
E.g. kusto-spark_3.0.0_2.12

2.  And we can do this going forward

3.  And firm up the docs to emphasize this change

**Review by anagha-microsoft — APPROVED** [review]
This construct is great-
kusto-spark_${spark.version.major}_${scala.version.major}

**Pull request merged**
